package org.ballistic.dreamjournalai.shared.dream_authentication

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import co.touchlab.kermit.Logger

actual object GoogleAuthProvider {
    actual suspend fun provideGoogleAuth(context: Any?): Result {
        val ctx = context as? Context
        if (ctx == null) {
            Logger.e { "[DJAI/GoogleAuthProv] provideGoogleAuth called with null context" }
            return Result.Error("Context is null")
        }

        // Try multiple resource names for client ID: prefer `default_web_client_id` (generated by google-services),
        // then `web_client_id` (compose resources), then `google_client_id` (shared androidMain), otherwise fall back to placeholder.
        val clientId = try {
            val names = listOf("default_web_client_id", "web_client_id", "google_client_id")
            var id: String? = null
            for (name in names) {
                val resId = ctx.resources.getIdentifier(name, "string", ctx.packageName)
                if (resId != 0) {
                    id = ctx.getString(resId)
                    Logger.d { "[DJAI/GoogleAuthProv] found client id resource: $name -> ${id.take(20)}..." }
                    break
                }
            }
            id ?: "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
        } catch (t: Throwable) {
            Log.w("GoogleAuthProvider", "Failed to read client id resource; using placeholder", t)
            "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
        }

        Logger.d { "[DJAI/GoogleAuthProv] launching CredentialManager.getCredential with clientId=$clientId" }
        val googleIdOption = GetSignInWithGoogleOption
            .Builder(clientId)
            .build()

        val request: GetCredentialRequest = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val credentialManager = CredentialManager.create(ctx)

        return try {
            val result = credentialManager.getCredential(request = request, context = ctx)
            val credObj = result.credential
            // Log credential class and details for debugging
            Logger.d { "[DJAI/GoogleAuthProv] CredentialManager returned credential class=${credObj::class.java.name}" }
            if (credObj is CustomCredential) {
                try {
                    // credObj.data is a Bundle — avoid unsafe conversions
                    val dataPreview = credObj.data.keySet().joinToString(",") { key -> "$key=${credObj.data.get(key)}" }.take(200)
                    Logger.d { "[DJAI/GoogleAuthProv] CustomCredential type=${credObj.type}, dataPreview=$dataPreview" }
                } catch (t: Throwable) {
                    Logger.d { "[DJAI/GoogleAuthProv] CustomCredential data logging failed: ${t.message}" }
                }
            }

            val credential = result.credential
            val isGoogleCreds = credential is CustomCredential &&
                    credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL

            if (isGoogleCreds) {
                val tokenResult = GoogleIdTokenCredential.createFrom(credential.data)
                Logger.d { "[DJAI/GoogleAuthProv] tokenResult.idToken length=${tokenResult.idToken.length}, id=${tokenResult.id.take(12)}" }
                val account = Account(idToken = tokenResult.idToken, accessTokenOrNonce = tokenResult.id)
                Result.Success(account)
            } else {
                Logger.i { "[DJAI/GoogleAuthProv] credential was not GoogleIdTokenCredential; returning Cancelled" }
                Result.Cancelled
            }
        } catch (ex: GetCredentialException) {
            // User cancelled the credential sheet or no credential available
            Logger.i { "[DJAI/GoogleAuthProv] GetCredentialException (probably cancelled) message=${ex.message}" }
            Result.Cancelled
        } catch (ex: Exception) {
            Logger.e { "[DJAI/GoogleAuthProv] provideGoogleAuth failed: ${ex.message}" }
            Result.Error(ex.message ?: ex.localizedMessage.orEmpty())
        }
    }
}
