platform :ios, '13.0'

# Use dynamic frameworks to avoid missing symbol issues with certain pods like RevenueCat
use_frameworks! :linkage => :dynamic

inhibit_all_warnings!

target 'iosApp' do
  # Local Compose shared module
  pod 'ComposeApp', :path => '../composeApp/shared'

  # RevenueCat SDK
  pod 'RevenueCat'
  # Firebase
#  pod 'FirebaseAnalytics'
#  pod 'FirebaseAuth'
#  pod 'FirebaseFirestore'
#  pod 'FirebaseFunctions'
#  pod 'FirebaseStorage'
#  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleSignIn'

end

# Ensure Swift version is set consistently for all pods
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
    end

    if target.name == 'ComposeApp'
      target.build_configurations.each do |config|
        config.build_settings.delete('ASSETCATALOG_COMPILER_APPICON_NAME')
      end
    end
  end
end
